name: blockchair
description: A simple API client for https://blockchair.com (Bitcoin only).
version: 0.1.3
author: Harm Aarts <harm@aarts.email>
homepage: https://github.com/haarts/blockchair

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
