name: blockchair
description: A simple API client for https://blockchair.com (Bitcoin only).
version: 0.1.2
homepage: https://github.com/inapay/blockchair

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
